import os
import re

def extract_info(file_path):
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()
            
        # Extract Title
        title_match = re.search(r'^##\s+(?:.*?)?\*\*Agent #(\d+):\s+(.*?)\*\*', content, re.MULTILINE)
        if title_match:
            agent_num = int(title_match.group(1))
            agent_name = title_match.group(2).strip()
            title = f"Agent #{agent_num}: {agent_name}"
        else:
            # Fallback for inconsistent formatting
            lines = content.split('\n')
            for line in lines:
                if line.strip().startswith('##'):
                    cleaned_line = line.replace('#', '').strip()
                    # Remove markdown bold/italic if present roughly
                    cleaned_line = cleaned_line.replace('*', '').strip()
                    title = cleaned_line
                    break
            else:
                title = os.path.basename(file_path)

        return title
    except Exception as e:
        print(f"Error reading {file_path}: {e}")
        return os.path.basename(file_path)

def generate_readme():
    base_dir = "."
    agents = []
    
    # Iterate from 1 to 100 to maintain order
    for i in range(1, 101):
        filename = f"{i}.md"
        file_path = os.path.join(base_dir, filename)
        
        if os.path.exists(file_path):
            title = extract_info(file_path)
            agents.append((i, title, filename))
        else:
            print(f"Warning: {filename} not found.")

    readme_content = """# 100 AI Agents Challenge 🤖

Welcome to the **100 AI Agents Challenge** repository! This project contains 100 different AI agents, each designed to solve specific problems or demonstrate unique capabilities using Large Language Models (LLMs) and various tools.

## 📚 Agent Directory

| # | Agent Name | Link |
|---|------------|------|
"""
    
    for _, title, filename in agents:
        # Title usually comes as "Agent #X: Name", we can split it or just put it in the Name column
        # Let's clean it up slightly for the table
        # If title is "Agent #1: Individualized Financial Advisory Agent"
        # We want: | 1 | Individualized Financial Advisory Agent | [View](./1.md) |
        
        display_name = title
        if ":" in title:
            parts = title.split(":", 1)
            if "Agent #" in parts[0]:
                display_name = parts[1].strip()
        
        # Helper to extract number from filename for the first column
        num = filename.replace('.md', '')
        
        readme_content += f"| {num} | {display_name} | [Documentation](./{filename}) |\n"

    readme_content += """
---
*Generated by [Antigravity](https://deepmind.google/technologies/gemini/)*
"""

    with open("README.md", "w", encoding="utf-8") as f:
        f.write(readme_content)
    
    print(f"Successfully generated README.md with {len(agents)} agents.")

if __name__ == "__main__":
    generate_readme()
